<?php

/**
 * FIA-NET categories
 * 
 * @var array
 */
$_fianetsceau_categories = array(
	1 => 'Alimentation & Gastronomie',
	2 => 'Animaux',
	3 => 'Armurerie',
	4 => 'Auto & Moto',
	5 => 'B&eacute;b&eacute;s et Enfants',
	6 => 'Culture & Divertissements',
	7 => 'Electrom&eacute;nager',
	8 => 'Ench&egrave;res & Achats group&eacute;s',
	9 => 'Finance aux particuliers',
	10 => 'Fleurs & Cadeaux',
	11 => 'Hifi, Photos & Vid&eacute;os',
	12 => 'Informatique & Logiciels',
	13 => 'Maison & Jardin',
	14 => 'Optique',
	15 => 'Sant&eacute; & Beaut&eacute',
	16 => 'Services aux professionnels',
	17 => 'Sport',
	18 => 'T&eacute;l&eacute;phonie & Communication',
	19 => 'Ventes priv&eacute;es',
	20 => 'V&ecirc;tements & Accessoires',
	21 => 'Vie pratique',
	22 => 'Voyage & Tourisme',
);


/**
 * FIA-NET subcategories
 * 
 * @var array
 */
$_fianetsceau_subcategories = array(
	2 => array('parent_id' => 1, 'label' => 'Chocolats & Confiseries'),
	3 => array('parent_id' => 1, 'label' => 'Alimentation g&eacute;n&eacute;rale'),
	4 => array('parent_id' => 1, 'label' => 'Produits du terroir'),
	5 => array('parent_id' => 1, 'label' => 'Vins & Spiritueux'),
	6 => array('parent_id' => 1, 'label' => 'Aliments pour animaux'),
	78 => array('parent_id' => 1, 'label' => 'Chocolats & Confiseries'),
	79 => array('parent_id' => 1, 'label' => 'Alimentation g&eacute;n&eacute;rale'),
	248 => array('parent_id' => 1, 'label' => 'Produits du terroir'),
	249 => array('parent_id' => 1, 'label' => 'Vins & Spiritueux'),
	264 => array('parent_id' => 2, 'label' => 'Animaux'),
	265 => array('parent_id' => 2, 'label' => 'Aliments pour animaux'),
	266 => array('parent_id' => 2, 'label' => 'Pharmacie pour animaux'),
	253 => array('parent_id' => 3, 'label' => 'Armes'),
	7 => array('parent_id' => 4, 'label' => 'Accessoires'),
	8 => array('parent_id' => 4, 'label' => 'Autre'),
	9 => array('parent_id' => 4, 'label' => 'Pneumatiques'),
	80 => array('parent_id' => 4, 'label' => 'Autoradios'),
	82 => array('parent_id' => 4, 'label' => 'Antivols'),
	84 => array('parent_id' => 4, 'label' => 'Produits d\'entretien'),
	86 => array('parent_id' => 4, 'label' => 'Pi&egrave;ces d&eacute;tach&eacute;es'),
	166 => array('parent_id' => 4, 'label' => 'Autos'),
	167 => array('parent_id' => 4, 'label' => '2 roues'),
	175 => array('parent_id' => 4, 'label' => 'Sport automobile'),
	186 => array('parent_id' => 4, 'label' => 'GPS'),
	231 => array('parent_id' => 4, 'label' => 'Casques & Combinaison moto'),
	232 => array('parent_id' => 4, 'label' => 'Caravanes & Camping-cars'),
	233 => array('parent_id' => 4, 'label' => 'Scooters'),
	234 => array('parent_id' => 4, 'label' => 'Pi&egrave;ces d&eacute;tach&eacute;es & Tuning'),
	235 => array('parent_id' => 4, 'label' => 'Voitures neuves & Occasions'),
	236 => array('parent_id' => 4, 'label' => 'Motos neuves & occasions'),
	237 => array('parent_id' => 4, 'label' => 'Autoradios & vid&eacute;o embarqu&eacute;e'),
	281 => array('parent_id' => 4, 'label' => 'Code de la route'),
	257 => array('parent_id' => 5, 'label' => 'Jeux & Jouets d\'&eacute;veil'),
	258 => array('parent_id' => 5, 'label' => 'Pu&eacute;riculture'),
	259 => array('parent_id' => 5, 'label' => 'Mobilier b&eacute;b&eacute;s'),
	260 => array('parent_id' => 5, 'label' => 'Faire-part & Cartes de voeux'),
	261 => array('parent_id' => 5, 'label' => 'Poussettes & Voyages'),
	262 => array('parent_id' => 5, 'label' => 'Hygi&egrave;ne'),
	263 => array('parent_id' => 5, 'label' => 'S&eacute;curit&eacute;'),
	272 => array('parent_id' => 5, 'label' => 'Mode b&eacute;b&eacute;s & Enfants'),
	10 => array('parent_id' => 6, 'label' => 'Arts graphiques'),
	11 => array('parent_id' => 6, 'label' => 'Autres'),
	12 => array('parent_id' => 6, 'label' => 'DVD'),
	13 => array('parent_id' => 6, 'label' => 'Jeux & Jouets'),
	14 => array('parent_id' => 6, 'label' => 'Jeux vid&eacute;os'),
	15 => array('parent_id' => 6, 'label' => 'Livres'),
	16 => array('parent_id' => 6, 'label' => 'Musique'),
	17 => array('parent_id' => 6, 'label' => 'Spectacles & &eacutes;v&egrave;nements'),
	87 => array('parent_id' => 6, 'label' => 'Art'),
	88 => array('parent_id' => 6, 'label' => 'Bande dessin&eacute;es'),
	90 => array('parent_id' => 6, 'label' => 'Collections et miniatures'),
	91 => array('parent_id' => 6, 'label' => 'Magazines'),
	92 => array('parent_id' => 6, 'label' => 'Cd-rom'),
	93 => array('parent_id' => 6, 'label' => 'Vid&eacute;os'),
	173 => array('parent_id' => 6, 'label' => 'Philat&eacute;lie'),
	185 => array('parent_id' => 6, 'label' => 'Consoles Vid&eacute;os'),
	244 => array('parent_id' => 6, 'label' => 'Instruments de musique'),
	245 => array('parent_id' => 6, 'label' => 'Livres & magazines'),
	246 => array('parent_id' => 6, 'label' => 'Vid&eacute;o DVD et Blu Ray'),
	271 => array('parent_id' => 6, 'label' => 'Consoles & Jeux vid&eacute;os'),
	273 => array('parent_id' => 6, 'label' => 'Mod&eacute;lisme'),
	280 => array('parent_id' => 6, 'label' => 'D&eacute;guisement'),
	283 => array('parent_id' => 6, 'label' => 'Enseignement'),
	286 => array('parent_id' => 6, 'label' => 'Vente de produits d&eacute;riv&eacute;s d\'artistes'),
	23 => array('parent_id' => 7, 'label' => 'R&eacute;frig&eacute;rateurs'),
	24 => array('parent_id' => 7, 'label' => 'Cong&eacute;lateurs'),
	25 => array('parent_id' => 7, 'label' => 'Lave-vaisselles'),
	26 => array('parent_id' => 7, 'label' => 'Micro-ondes'),
	27 => array('parent_id' => 7, 'label' => 'Fours'),
	28 => array('parent_id' => 7, 'label' => 'Cuisini&egrave;res'),
	100 => array('parent_id' => 7, 'label' => 'Hottes aspirantes'),
	101 => array('parent_id' => 7, 'label' => 'Tables de cuisson'),
	102 => array('parent_id' => 7, 'label' => 'Appareils culinaires'),
	103 => array('parent_id' => 7, 'label' => 'Laves-linge'),
	104 => array('parent_id' => 7, 'label' => 'S&egrave;ches-linge'),
	105 => array('parent_id' => 7, 'label' => 'Aspirateurs'),
	106 => array('parent_id' => 7, 'label' => 'S&egrave;ches-cheveux'),
	108 => array('parent_id' => 7, 'label' => 'Rasoirs'),
	109 => array('parent_id' => 7, 'label' => 'Epilateurs'),
	110 => array('parent_id' => 7, 'label' => 'P&egrave;ses-personne'),
	111 => array('parent_id' => 7, 'label' => 'Fers &agrave;  repasser'),
	169 => array('parent_id' => 7, 'label' => 'Produits d\'entretien'),
	183 => array('parent_id' => 7, 'label' => 'Accessoires'),
	188 => array('parent_id' => 7, 'label' => 'Climatisation'),
	200 => array('parent_id' => 7, 'label' => 'Machines &agrave;  coudre'),
	201 => array('parent_id' => 7, 'label' => 'Cafeti&egrave;res & Expresso'),
	202 => array('parent_id' => 7, 'label' => 'Caves &agrave;  vin'),
	203 => array('parent_id' => 7, 'label' => 'Petit &eacute;lectrom&eacute;nager'),
	204 => array('parent_id' => 7, 'label' => 'Centrales vapeurs & Fers &agrave;  repasser'),
	205 => array('parent_id' => 7, 'label' => 'M&eacute;nage & Produits d\'entretien'),
	206 => array('parent_id' => 7, 'label' => 'Chauffage, Climatisation & Energies renouvelables'),
	29 => array('parent_id' => 8, 'label' => 'Achats group&eacute;s'),
	30 => array('parent_id' => 8, 'label' => 'Clubs de consommateurs'),
	31 => array('parent_id' => 8, 'label' => 'Ench&egrave;res'),
	32 => array('parent_id' => 8, 'label' => 'Ench&egrave;res invers&eacute;es'),
	254 => array('parent_id' => 9, 'label' => 'Assurance'),
	255 => array('parent_id' => 9, 'label' => 'Informations juridiques'),
	256 => array('parent_id' => 9, 'label' => 'Banque & Finance'),
	290 => array('parent_id' => 9, 'label' => 'Rachat d\'or'),
	33 => array('parent_id' => 10, 'label' => 'Service d\'aide pour les cadeaux'),
	34 => array('parent_id' => 10, 'label' => 'Cartes'),
	35 => array('parent_id' => 10, 'label' => 'Fleurs'),
	36 => array('parent_id' => 10, 'label' => 'Souvenirs'),
	112 => array('parent_id' => 10, 'label' => 'Chocolats & Confiseries'),
	267 => array('parent_id' => 10, 'label' => 'Cartes & Papeterie'),
	268 => array('parent_id' => 10, 'label' => 'Bons d\'achats & Ch&egrave;ques cadeaux'),
	269 => array('parent_id' => 10, 'label' => 'Gadgets & Cadeaux personnalis&eacute;s'),
	270 => array('parent_id' => 10, 'label' => 'Escapades & Coffrets cadeaux'),
	278 => array('parent_id' => 10, 'label' => 'Accessoires fumeurs'),
	142 => array('parent_id' => 11, 'label' => 'Radios cassettes'),
	143 => array('parent_id' => 11, 'label' => 'Autoradios'),
	145 => array('parent_id' => 11, 'label' => 'Vid&eacute;oprojecteurs'),
	146 => array('parent_id' => 11, 'label' => 'Appareils photo'),
	147 => array('parent_id' => 11, 'label' => 'Lecteur mp3'),
	148 => array('parent_id' => 11, 'label' => 'T&eacute;l&eacute;viseurs'),
	149 => array('parent_id' => 11, 'label' => 'Camescopes'),
	150 => array('parent_id' => 11, 'label' => 'Chaines hifi'),
	152 => array('parent_id' => 11, 'label' => 'Baladeurs'),
	153 => array('parent_id' => 11, 'label' => 'Amplificateurs'),
	154 => array('parent_id' => 11, 'label' => 'Enceintes'),
	155 => array('parent_id' => 11, 'label' => 'Tables de mixage'),
	156 => array('parent_id' => 11, 'label' => 'Lecteurs DVD'),
	158 => array('parent_id' => 11, 'label' => 'Magn&eacute;toscopes'),
	161 => array('parent_id' => 11, 'label' => 'Tirages photos'),
	177 => array('parent_id' => 11, 'label' => 'Accessoires'),
	179 => array('parent_id' => 11, 'label' => 'Home cin&eacute;ma'),
	196 => array('parent_id' => 11, 'label' => 'Enregistreurs'),
	197 => array('parent_id' => 11, 'label' => 'D&eacute;veloppement photos'),
	198 => array('parent_id' => 11, 'label' => 'Lecteur DVD & Blu Ray'),
	199 => array('parent_id' => 11, 'label' => 'Lecteur MP3 & Baladeurs'),
	37 => array('parent_id' => 12, 'label' => 'Consommables'),
	38 => array('parent_id' => 12, 'label' => 'Logiciels'),
	39 => array('parent_id' => 12, 'label' => 'Ordinateurs'),
	40 => array('parent_id' => 12, 'label' => 'P&eacute;riph&eacute;riques'),
	41 => array('parent_id' => 12, 'label' => 'Pi&egrave;ces d&eacute;tach&eacute;es'),
	42 => array('parent_id' => 12, 'label' => 'T&eacute;l&eacute;chargements'),
	113 => array('parent_id' => 12, 'label' => 'Imprimantes'),
	114 => array('parent_id' => 12, 'label' => 'Lecteurs & Graveurs'),
	115 => array('parent_id' => 12, 'label' => 'Moniteurs'),
	116 => array('parent_id' => 12, 'label' => 'Cartes Graphiques'),
	117 => array('parent_id' => 12, 'label' => 'Composants'),
	118 => array('parent_id' => 12, 'label' => 'Assistants personnels'),
	119 => array('parent_id' => 12, 'label' => 'Modems'),
	120 => array('parent_id' => 12, 'label' => 'Scanners'),
	159 => array('parent_id' => 12, 'label' => 'Portables'),
	176 => array('parent_id' => 12, 'label' => 'Editeurs'),
	184 => array('parent_id' => 12, 'label' => 'Accessoires'),
	207 => array('parent_id' => 12, 'label' => 'Mini PC'),
	208 => array('parent_id' => 12, 'label' => 'Cables & Connectiques'),
	209 => array('parent_id' => 12, 'label' => 'GPS'),
	210 => array('parent_id' => 12, 'label' => 'R&eacute;seau'),
	211 => array('parent_id' => 12, 'label' => 'D&eacute;pannage informatique'),
	212 => array('parent_id' => 12, 'label' => 'Stockage'),
	213 => array('parent_id' => 12, 'label' => 'Ordinateurs PC & Mac'),
	214 => array('parent_id' => 12, 'label' => 'Ordinateurs Portables'),
	215 => array('parent_id' => 12, 'label' => 'Consommables & Accessoires'),
	284 => array('parent_id' => 12, 'label' => 'Tablettes'),
	285 => array('parent_id' => 12, 'label' => 'Accessoires pour tablettes'),
	19 => array('parent_id' => 13, 'label' => 'Bricolage'),
	20 => array('parent_id' => 13, 'label' => 'Jardinage'),
	21 => array('parent_id' => 13, 'label' => 'Fournitures & Mobiliers'),
	22 => array('parent_id' => 13, 'label' => 'Design'),
	94 => array('parent_id' => 13, 'label' => 'D&eacute;coration'),
	95 => array('parent_id' => 13, 'label' => 'Linge de maison'),
	96 => array('parent_id' => 13, 'label' => 'Luminaires'),
	97 => array('parent_id' => 13, 'label' => 'Mobilier de jardin'),
	98 => array('parent_id' => 13, 'label' => 'Vaisselles'),
	99 => array('parent_id' => 13, 'label' => 'Autres'),
	170 => array('parent_id' => 13, 'label' => 'Produits d\'entretien'),
	181 => array('parent_id' => 13, 'label' => 'Arts de la table'),
	187 => array('parent_id' => 13, 'label' => 'Salles de bain'),
	216 => array('parent_id' => 13, 'label' => 'Fen&ecirc;tres, Volets & Stores'),
	217 => array('parent_id' => 13, 'label' => 'Animalerie'),
	218 => array('parent_id' => 13, 'label' => 'Cuisines'),
	219 => array('parent_id' => 13, 'label' => 'Ameublement'),
	220 => array('parent_id' => 13, 'label' => 'Piscines'),
	221 => array('parent_id' => 13, 'label' => 'Maisons en bois'),
	222 => array('parent_id' => 13, 'label' => 'Chauffage, Climatisation & Energies renouvelables'),
	223 => array('parent_id' => 13, 'label' => 'Barbecues, Plancha & Accessoires'),
	224 => array('parent_id' => 13, 'label' => 'Protections & Alarmes'),
	225 => array('parent_id' => 13, 'label' => 'Literie'),
	227 => array('parent_id' => 13, 'label' => 'Bricolage & Outillage'),
	228 => array('parent_id' => 13, 'label' => 'Mobilier & Am&eacute;nagement d\'exterieur'),
	229 => array('parent_id' => 13, 'label' => 'Art de la table et de la cuisine'),
	277 => array('parent_id' => 13, 'label' => 'Stickers & Adh&eacute;sifs'),
	275 => array('parent_id' => 14, 'label' => 'Lunettes de soleil'),
	276 => array('parent_id' => 14, 'label' => 'Lunettes & Lentilles'),
	43 => array('parent_id' => 15, 'label' => 'Soins des cheveux'),
	44 => array('parent_id' => 15, 'label' => 'Soins du corps'),
	45 => array('parent_id' => 15, 'label' => 'Parfums'),
	46 => array('parent_id' => 15, 'label' => 'Soins du visage'),
	47 => array('parent_id' => 15, 'label' => 'Sexualit&eacute;'),
	48 => array('parent_id' => 15, 'label' => 'Animaux'),
	121 => array('parent_id' => 15, 'label' => 'Produits biologiques'),
	122 => array('parent_id' => 15, 'label' => 'Produits di&eacute;t&eacute;tiques'),
	123 => array('parent_id' => 15, 'label' => 'Parapharmacie'),
	124 => array('parent_id' => 15, 'label' => 'Minceur'),
	125 => array('parent_id' => 15, 'label' => 'Cosm&eacute;tiques'),
	157 => array('parent_id' => 15, 'label' => 'B&eacute;b&eacute;'),
	163 => array('parent_id' => 15, 'label' => 'Lunettes'),
	238 => array('parent_id' => 15, 'label' => 'Appareils sant&eacute; beaut&eacute;'),
	239 => array('parent_id' => 15, 'label' => 'Produits di&eacute;t&eacute;tiques & Bien-&ecirc;tre'),
	240 => array('parent_id' => 15, 'label' => 'Cosm&eacute;tiques & Cosm&eacute;tiques bio'),
	241 => array('parent_id' => 15, 'label' => 'Soins du corps et du visage'),
	242 => array('parent_id' => 15, 'label' => 'Intimit&eacute; & Pr&eacute;servatifs'),
	243 => array('parent_id' => 15, 'label' => 'Lentilles de contact & Lunettes de vue'),
	288 => array('parent_id' => 15, 'label' => 'Accessoires'),
	59 => array('parent_id' => 16, 'label' => 'Divers'),
	60 => array('parent_id' => 16, 'label' => 'Ench&egrave;res professionnelles'),
	61 => array('parent_id' => 16, 'label' => 'Formation'),
	62 => array('parent_id' => 16, 'label' => 'Fournitures & Mobiliers'),
	63 => array('parent_id' => 16, 'label' => 'Prestataires Internet'),
	64 => array('parent_id' => 16, 'label' => 'Produits agricoles'),
	172 => array('parent_id' => 16, 'label' => 'Information juridique'),
	65 => array('parent_id' => 17, 'label' => 'Ev&egrave;nements'),
	66 => array('parent_id' => 17, 'label' => 'Mat&eacute;riel'),
	67 => array('parent_id' => 17, 'label' => 'Di&eacute;t&eacute;tique'),
	68 => array('parent_id' => 17, 'label' => 'V&ecirc;tements'),
	182 => array('parent_id' => 17, 'label' => 'Chaussures'),
	247 => array('parent_id' => 17, 'label' => 'Fitness & Di&eacute;t&eacute;tique'),
	279 => array('parent_id' => 17, 'label' => 'Ski'),
	127 => array('parent_id' => 18, 'label' => 'Accessoires'),
	128 => array('parent_id' => 18, 'label' => 'T&eacute;l&eacute;phones fixes'),
	129 => array('parent_id' => 18, 'label' => 'T&eacute;l&eacute;phones mobiles'),
	130 => array('parent_id' => 18, 'label' => 'Fax'),
	160 => array('parent_id' => 18, 'label' => 'Abonnements'),
	178 => array('parent_id' => 18, 'label' => 'Achats de minute'),
	230 => array('parent_id' => 18, 'label' => 'Abonnements Internet & T&eacute;l&eacute;phonique'),
	274 => array('parent_id' => 19, 'label' => 'Ventes priv&eacute;es'),
	69 => array('parent_id' => 20, 'label' => 'Accessoires'),
	70 => array('parent_id' => 20, 'label' => 'Bijoux'),
	71 => array('parent_id' => 20, 'label' => 'Chaussures'),
	72 => array('parent_id' => 20, 'label' => 'Lingerie'),
	73 => array('parent_id' => 20, 'label' => 'Maroquinerie'),
	74 => array('parent_id' => 20, 'label' => 'Mode enfants'),
	75 => array('parent_id' => 20, 'label' => 'Mode femme'),
	76 => array('parent_id' => 20, 'label' => 'Mode homme'),
	77 => array('parent_id' => 20, 'label' => 'Montres'),
	126 => array('parent_id' => 20, 'label' => 'Bagagerie'),
	164 => array('parent_id' => 20, 'label' => 'Lunettes'),
	190 => array('parent_id' => 20, 'label' => 'V&ecirc;tement femme enceinte'),
	191 => array('parent_id' => 20, 'label' => 'Jeans'),
	192 => array('parent_id' => 20, 'label' => 'Mode b&eacute;b&eacute;s & Enfants'),
	193 => array('parent_id' => 20, 'label' => 'Lunettes de soleil'),
	194 => array('parent_id' => 20, 'label' => 'Accessoires de mode'),
	195 => array('parent_id' => 20, 'label' => 'Bijoux & Montres'),
	287 => array('parent_id' => 20, 'label' => 'Vente de produits d&eacute;riv&eacute;s d\'artistes'),
	289 => array('parent_id' => 20, 'label' => 'Militaire'),
	49 => array('parent_id' => 21, 'label' => 'Actualit&eacute;s & Presse'),
	50 => array('parent_id' => 21, 'label' => 'Assurance'),
	51 => array('parent_id' => 21, 'label' => 'Banque & Finance'),
	52 => array('parent_id' => 21, 'label' => 'Cartes & Plans'),
	53 => array('parent_id' => 21, 'label' => 'Galeries marchandes'),
	54 => array('parent_id' => 21, 'label' => 'Fournitures & Mobiliers'),
	55 => array('parent_id' => 21, 'label' => 'Petites annonces'),
	56 => array('parent_id' => 21, 'label' => 'Rencontres'),
	57 => array('parent_id' => 21, 'label' => 'Science'),
	58 => array('parent_id' => 21, 'label' => 'Animaux'),
	162 => array('parent_id' => 21, 'label' => 'Tirages photos'),
	165 => array('parent_id' => 21, 'label' => 'Immobilier'),
	168 => array('parent_id' => 21, 'label' => 'Papeterie'),
	171 => array('parent_id' => 21, 'label' => 'Information juridique'),
	174 => array('parent_id' => 21, 'label' => 'Divers'),
	180 => array('parent_id' => 21, 'label' => 'Armes'),
	189 => array('parent_id' => 21, 'label' => 'S&eacute;curit&eacute;'),
	226 => array('parent_id' => 21, 'label' => 'Mobilier d\'int&eacute;rieur'),
	250 => array('parent_id' => 21, 'label' => 'Faire-part & Cartes de voeux'),
	251 => array('parent_id' => 21, 'label' => 'Imprimerie & Cartes de visite'),
	252 => array('parent_id' => 21, 'label' => 'Sciences'),
	282 => array('parent_id' => 21, 'label' => 'Code de la route'),
	131 => array('parent_id' => 22, 'label' => 'Billets d\'avion'),
	132 => array('parent_id' => 22, 'label' => 'Location de voitures'),
	133 => array('parent_id' => 22, 'label' => 'H&ocirc;tels'),
	134 => array('parent_id' => 22, 'label' => 'S&eacute;jours'),
	135 => array('parent_id' => 22, 'label' => 'Circuits'),
	136 => array('parent_id' => 22, 'label' => 'Croisi&egrave;res'),
	137 => array('parent_id' => 22, 'label' => 'Logements'),
	138 => array('parent_id' => 22, 'label' => 'Week-ends'),
	139 => array('parent_id' => 22, 'label' => 'Cartes & Guides'),
	140 => array('parent_id' => 22, 'label' => 'Derni&egrave;re minute'),
	141 => array('parent_id' => 22, 'label' => 'Bagagerie'),
);

